name: drink
description: A new Flutter project. 

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl_phone_field:
    git:
      url: https://github.com/ahsanalidev/intl_phone_field.git
  another_flushbar: ^1.10.17
  auto_size_text: ^2.1.0
  carousel_slider: ^2.3.1
  credit_card_validator: ^1.2.0
  cupertino_icons: ^1.0.2
  date_format: ^1.0.9
  datetime_picker_formfield: ^2.0.0
  dio: ^4.0.0-beta4
  equatable: ^1.2.5
  firebase_auth: ^1.0.0
  firebase_core: ^1.0.0
  firebase_messaging: ^9.1.1
  fluster: ^1.1.2
  flutter_bloc: ^6.1.1
  flutter_cupertino_date_picker_fork: ^1.0.1
  flutter_facebook_login: ^3.0.0
  flutter_html: ^2.0.0-nullsafety.0
  flutter_xlider: ^3.4.0
  fluttertoast: ^7.1.6
  font_awesome_flutter: ^8.11.0
  geolocator: ^7.0.1
  google_maps_flutter: ^2.0.1
  google_maps_flutter_web: ^0.2.1
  google_maps_webservice: ^0.0.20-nullsafety.0
  google_sign_in: ^5.0.1
  image_cropper: ^1.4.0
  image_picker: any
  intl: any
  mask_text_input_formatter: ^1.2.1
  percent_indicator: ^2.1.9+1
  qr_flutter: ^3.2.0
  rxdart: ^0.25.0
  share: ^2.0.1
  shared_preferences: ^2.0.6
  sign_in_with_apple: ^2.5.4
  sizer: ^2.0.13
  sliding_up_panel: ^1.0.2
  stripe_payment: ^1.0.10
  timer_count_down: ^1.0.4+1
  uuid: any
  http: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  build_runner: ^2.0.5
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icons.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Black.ttf
        - asset: fonts/Montserrat-BlackItalic.ttf
        - asset: fonts/Montserrat-Bold.ttf
        - asset: fonts/Montserrat-BoldItalic.ttf
        - asset: fonts/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat-ExtraBoldItalic.ttf
        - asset: fonts/Montserrat-ExtraLight.ttf
        - asset: fonts/Montserrat-ExtraLightItalic.ttf
        - asset: fonts/Montserrat-Italic.ttf
        - asset: fonts/Montserrat-Light.ttf
        - asset: fonts/Montserrat-LightItalic.ttf
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-MediumItalic.ttf
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-SemiBold.ttf
        - asset: fonts/Montserrat-SemiBoldItalic.ttf
        - asset: fonts/Montserrat-Thin.ttf
        - asset: fonts/Montserrat-ThinItalic.ttf

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/privacy.html
    - assets/map_style.json
    - assets/map_style_light.json
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
